### PR TITLE
chore: qpid dependency

### PR DESCRIPTION
**Pull request by squakez**
Closes [ENTESB-16991](https://issues.redhat.com/browse/ENTESB-16991)

### CODE REVIEW

**Comment by squakez** [comment]
FYI @heiko-braun @tplevko

**Comment by heiko-braun** [comment]
Coo,, thanks @squakez . Did you do q quick dry run to check if it works?

**Comment by squakez** [comment]
> Cool, thanks @squakez . Did you do a quick dry run to check if it works?

Yep, tested successfully on my side.

**Comment by heiko-braun** [comment]
@tplevko This doesn't require another build and should work as is. Feel free to get going when ready.

**Pull request merged**
